### ISSUE TITLE
Support binary serialization

### ISSUE THREAD

**Issue by roubachof** [markmeeus/MarcelloDB#34]
Would be nice to be able to inject a serializer implementation, so user could use the serializer they like best according to their needs.
For example, a binary serialization would be good for perf.

**Comment by markmeeus** [comment]
Hi Roubachof,

That's definitely a feature I have been thinking about.
The only thing that's holding me back on it is that I may want to implement a generic data viewer.
This will become impossible if the data was serialized with custom code.

I'll think about it a bit more , and put it on the roadmap somewhere.

A note about performance:
MarcelloDB uses json.net to do BSON serialization of most of the data, including it's own inner data structures.
I'm currently working on code that will use custom serializers for most of the inner data structures, which will (hopefully) have a great impact on (insert/update) performance. And even more when using IndexDefinition.

Could you tell me a bit more about the performance issues you are seeing?

**Comment by markmeeus** [comment]
I'm closing this issue for now. 
Custom serializers will not be part of v1 because allowing custom formats may add too much constraints for other features.
I might add a way to use a more lower-level serialization mechanism for performance reasons later on, but no custom custom serializers for now.

Thanks again for reporting it.
