### ISSUE TITLE
Export/Import functionality

### ISSUE THREAD

**Issue by simbadltd** [markmeeus/MarcelloDB#46]
Hello Mark!

I'm working on upgrading my data from 0.4.x to 0.6.x version of MarcelloDB. And I've decided to go the following way:
1. Export all data from 0.4.x MarcelloDB into json files
2. Upgrade MarcelloDB from 0.4.x to 0.6x
3. Import all data from json files into MarcelloDB 0.6.x

So, I was unable to do it without custom code. I wrote smth like this:
```
public static class CollectionJsonExportImport
    {
        public static void ExportToFile<T, TID, TIndexDef>(
            this MarcelloDB.Collections.Collection<T, TID, TIndexDef> collection, string filePath)
            where TIndexDef : IndexDefinition<T>, new()
        {
            var contents = ExportToJson(collection);
            File.WriteAllText(filePath, contents);
        }

        public static string ExportToJson<T, TID, TIndexDef>(
            this MarcelloDB.Collections.Collection<T, TID, TIndexDef> collection)
            where TIndexDef : IndexDefinition<T>, new()
        {
            var items = collection.All.ToList();
            var result = JsonConvert.SerializeObject(items,
                new JsonSerializerSettings {TypeNameHandling = TypeNameHandling.All});
            return result;
        }

        public static void ImportFromFile<T, TID, TIndexDef>(
            this MarcelloDB.Collections.Collection<T, TID, TIndexDef> collection, string filePath)
            where TIndexDef : IndexDefinition<T>, new()
        {
            var contents = File.ReadAllText(filePath);
            var items = JsonConvert.DeserializeObject<List<T>>(contents,
                new JsonSerializerSettings {TypeNameHandling = TypeNameHandling.All});

            foreach (var item in items)
            {
                collection.Persist(item);
            }
        }
    }
```

May be it would be useful for other guys. Pls consider to include such functionality into MarcelloDB library.

**Comment by markmeeus** [comment]
Hi simbadltd,

Thank you for sharing this.

When moving data from 0.4 to 0.5 or 0.6, there is no other way than to get all data out using 0.4 and persisting it again using 0.6.
From 1.0, which will be released soon, all 1.x versions will be able to read data created with older versions. 
I didn't want to carry this burden in the 0.x versions since I wanted the freedom to radically change the data format without having to worry about backwards compatibility.

There are a few things I would like to double check before releasing 1.0, so it may even happen again going from 0.6 to 1.0. 
But that should be the last compatibility issue.

About your proposal, I'm not going to include it in MarcelloDB since it's not really a part of MarcelloDB responsibility. 
If users have another scenario where data needs to be exported to a json file, I'm sure they'll figure it out, just like you did :-)

It might make sense to have it in a MarcelloDBTools library, but I currently have no time to maintain such a thing. 
(You can consider this a hint :-) )
