### ISSUE TITLE
Can MarcelloDB create an in-memory database?

### ISSUE THREAD

**Issue by kameko** [markmeeus/MarcelloDB#51]
If not, I guess this is a feature request.

**Comment by markmeeus** [comment]
Hi there,

Yes, MarcelloDB can work as an in memory database.
You can achieve this by implementing a specific Platform object which doesn't use the file system, but works on memory streams directly.

Take look at this code: 
https://github.com/markmeeus/MarcelloDB/tree/master/MarcelloDB.Test/TestStream

I you copy those 2 files in your project and initialize your Session with the TestPlatform (or rename it as you want) you'll end up with a fully function in-memory MarcelloDB.
```csharp
new Session(new TestPlatform(), "/path/does/not/matter");
```
It's a bit undocumented since I want to keep the freedom to change the IPlatform interface.

thanks for asking!

**Comment by kameko** [comment]
Thank you! That's really helpful. I copied those files and credited them to you.
