### ISSUE TITLE
Saving a C# Object with ImageSource (Xamarin.Forms) causing Newtonsoft Error

### ISSUE THREAD

**Issue by kmccmk9** [markmeeus/MarcelloDB#60]
Hello,

As my title states, trying to save the following C# object: results in this error:
```
public class PlaceListItem : BaseDataObject
{
	public string Address { get; set; }
	public string PlaceId { get; set; }
	public ImageSource PlacePhoto { get; set; }
	public string PlaceName { get; set; }
	public double PlaceRating { get; set; }
	public string PlaceHours { get; set; }
}
```
Results in:
`Newtonsoft.Json.JsonSerializationException: Error getting value from 'Capacity' on 'System.IO.MemoryStream'.`

However if I don't specify an PlacePhoto (ImageSource), it saves perfectly fine with all other fields.

**Comment by markmeeus** [comment]
Hi Kyle,

That actually makes sense.
MarcelloDB uses json.net under the hood to serialize your objects to bson (think json, but stored in a binary format).
So, json.net is complaining that it cannot serialize ImageSource. (It is actually trying to serialize a memory stream by enumarating its properties).
So you need to help json.net to do this.


One way to do this is to add a JsonProperty attribute on your PlacePhoto property, in which you specifiy a converter type to read and write this type of data (ImageSource)
```cs
  [JsonProperty(ItemConverterType=typeof(ImageSourceConverter))]
  public ImageSource PlacePhoto { get; set; }
```

Of course, you need an implementation of ImageSourceConverter:
```cs
public class ImageSourceConverter : JsonConverter{
    public override bool CanConvert (Type objectType)
    {
      return objectType == typeof (ImageSource);
    }
    public override object ReadJson (JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
    {
        //TODO: convert reader.Value to ImageSource and return
        return null;
    }
    public override void WriteJson (JsonWriter writer, object value, JsonSerializer serializer)
    {
        //TODO: write image Source to writer
     }
}
```

Leaving the todo's for you to figure out :)

As a sidenote, you have to realize that MarcelloDB will read and deserialize every time you load the object. So if you enumerate the collection, it will load all images, which will slow down your app.
If you are sure you will always need the image when you load it, it doesn't matter, otherwise you might be better of storing all images in a separate collection.

```cs
public class PlaceListItem : BaseDataObject
{
	public string Address { get; set; }
	public string PlaceId { get; set; }
	public string PlacePhotoId { get; set; }
	public string PlaceName { get; set; }
	public double PlaceRating { get; set; }
	public string PlaceHours { get; set; }
}

public class Photo 
{
    public string id { get; set; }
    [JsonProperty(ItemConverterType=typeof(ImageSourceConverter))]
    public ImageSource Photo { get; set; }
}
```

**Comment by kmccmk9** [comment]
Hi, thank you for taking the time to write all of that. I had been reading more about about ImageSource and arrived at a similar conclusion that since it was a Stream it couldn't be serialized. So I'm going to play around with the best/most efficient way to convert to/from streams and I'll report back. Maybe something like this would be worth implementing directly into the core of Marcello?

**Comment by markmeeus** [comment]
Hi Kyle,

For now I don't think custom serialisation logic belongs in MarcelloDB.
But I think some extra documentation pages would already help other users.
