### ISSUE TITLE
Can marcello run on asp.net core ?

### ISSUE THREAD

**Issue by egarim** [markmeeus/MarcelloDB#68]
Hi 
I have created a rest API using asp.net core when I try to do the Marcello setup I cant pick 
uwp or netfx, none of them are available on .net core

**Comment by markmeeus** [comment]
Hi,

MarcelloDB supports .net standard 1.1, so the core could definitely run on .net core.
However, there is currently no 'platform' implementation for .net core.
I think it should be pretty straightforward to have an implementation.
However, I currently don't have the bandwidth to have a look at this, If you want to have a go at it, I'll gladly help you out!

Now that's said, I do want to point out that MarcelloDB is probably a bad choice as a database to use on the server. There can only be one executing transaction, so other threads will get blocked until the previous transaction is done.
Also horizontal scalability is non existent since it runs straight from disk. (don't try to share the session folder ;-) )
So unless you know upfront that you are not going to have to deal with some substantial load, I would advise against it .

Also, please make sure you use 1.0.6, I recently found a critical file corrupting issue.

**Comment by egarim** [comment]
Hi markmeeus
Thanks for your answer, actually the reason to use Marcello on the server is for some sample API (read-only data). Thanks for your answer anyway

**Comment by markmeeus** [comment]
haha, that's actually a good use case indeed :-)
It will still be single threaded, but lookups should be pretty fast.

**Comment by markmeeus** [comment]
If you look at the .netfx platform code, you'll see it's only a few lines. Reading and writing data to a file basically.
